
services:
  hr-bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1  # Enable build caching
    image: hr-bot:latest
    container_name: hr-bot
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ENV_MODE=production
    volumes:
      - ./vectorstore:/app/vectorstore  # Persist vector store between container restarts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command: http hr-bot:8080
    env_file:
      - .env
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    ports:
      - "4040:4040"  # ngrok web interface
    depends_on:
      - hr-bot
