Fixing bot.py embedding model to match vectorstore dimensions...
 = " src\\core\\bot.py\; = Get-Content -Path -Raw; = -replace \BAAI/bge-base-en-v1.5\, \BAAI/bge-small-en-v1.5\; Set-Content -Path -Value -Encoding utf8; echo \Fixed bot.py - changed to BAAI/bge-small-en-v1.5 model\
