services:
  - type: web
    name: cmu-hr-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_APP_TOKEN
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: MAX_TOKENS
        value: "2048"
      - key: LLM_TIMEOUT
        value: "30"
      - key: MAX_RETRIEVED_DOCS
        value: "15"
      - key: ENV_MODE
        value: "production"
    healthCheckPath: /api/status
    healthCheckTimeout: 10
    autoDeploy: true 